# -*- coding: utf-8 -*-
"""HeartDiseaseApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sW7aJhOKXHkr94kv6mmOO-F1hMevRlTJ
"""

import numpy as np
import pandas as pd
import pickle
import streamlit as st

pipe = pickle.load(open('new_pipe.pkl','rb'))

st.title('Heart Disease Prediction Web App ❤️')
st.write('Enter patient details below: ')
Age  = st.number_input('Age',min_value=1,max_value=120,value=30)
Sex  = st.selectbox('Sex',['M','F'])
ChestPainType = st.selectbox('Chest Pain Type',['ASY','NAP','ATA','TA'])
RestingBP = st.number_input('Resting Blood Pressure',min_value=50,max_value=250,value=120)
Cholesterol = st.number_input('Cholesterol',min_value=50,max_value=600,value=200)
FastingBS = st.selectbox('Fasting Blood Sugar',['0','1'])
RestingECG = st.selectbox('Resting ElectroCardiogram',['Normal', 'ST', 'LVH'])
MaxHR = st.number_input('Maximum Heart Rate',min_value=50,max_value=250,value=150)
ExerciseAngina = st.selectbox('Exercise Angina',['N','Y'])
Oldpeak = st.number_input('Oldpeak',min_value=0.0,max_value=10.0,value=1.0,step=0.1)
ST_Slope = st.selectbox('ST Slope',['Up', 'Flat', 'Down'])

# --------convert input to DataFrame-----------
input_data = pd.DataFrame([{
    'Age': Age,
    'Sex': Sex,
    'ChestPainType': ChestPainType,
    'RestingBP': RestingBP,
    'Cholesterol': Cholesterol,
    'FastingBS': FastingBS,
    'RestingECG': RestingECG,
    'MaxHR': MaxHR,
    'ExerciseAngina': ExerciseAngina,
    'Oldpeak': Oldpeak,
    'ST_Slope': ST_Slope
}])

# ------------predict---------------
if st.button('Predict'):
    prediction = pipe.predict(input_data)[0]

    if prediction == 1:
        st.error ('⚠️ High risk of Heart Disease')
    else:
      st.success('✔️ Low risk of Heart Disease')